server:
  port: 5000
  error:
    include-message: always

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/resume_db}
      database: resume_db
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

aws:
  region: ${AWS_REGION}
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID}
    client-id: ${COGNITO_CLIENT_ID}
    client-secret: ${COGNITO_CLIENT_SECRET}
    domain: ${COGNITO_DOMAIN}
    redirect-url: ${COGNITO_REDIRECT_URL}
    logout-url: ${COGNITO_LOGOUT_URL}
  sqs:
    queue-url: ${SQS_QUEUE_URL}

app:
  redis:
    jobs:
      host: ${REDIS_HOST_2:localhost}
      port: ${REDIS_PORT_2:6379}
      password: ${REDIS_PASSWORD_2:}
  ai:
    google-api-key: ${GOOGLE_API_KEY}
    openai-api-key: ${OPENAI_API_KEY}
  upload:
    allowed-extensions:
      - pdf
    upload-dir: static/uploads

logging:
  level:
    com.linkedinjobassistant: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data: INFO

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  allow-credentials: true
  max-age: 3600
